### ISSUE TITLE
Incorrect CACHE-CONTROL header value

### ISSUE THREAD

**Issue by SiMet** [openhome/ohNet#17]
Currently in Alives messages there is CACHE-CONTROL values as:
max-age = value

According to UCTT there shouldn't be spaces between max-age,equal character and value

ERROR M-SEARCH response: extra characters in max-age, ex. spaces next to equal character
ERROR Validation result of CACHE-CONTROL header: FAILED

It's easy to fix. In OpenHome/Net/Ssdp.cpp remove stream.Write(Ascii::kSp); in lines 224 and 226.

I didn't look if there is something in tests.

**Comment by SimonChisholm** [comment]
The UPnP architecture spec appears to mandate that these spaces are present (see the format of ssdp:alive and ssdp:byebye messages in http://www.upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.0.pdf).  At the very least, I can't see any mention of spaces being invalid.

Alive notifications are fundamental to UPnP; we haven't had any previous reports about the format of these messages being invalid.  I'm not familiar with UCTT.  Can you point me towards the specification we're breaking please, along with the tools that provided the output you quoted?

**Comment by SiMet** [comment]
Dear Simon,
I couldn't provide you UCTT beacase access to the UPnP Certification Test Tool is limited to UPnP Forum Members. It's tool required to certification. I also didn't find any infromation that could confirm that while spaces are forbidden. Only one sentence:
 "CACHE-CONTROL
... Field value MUST have the max-age directive (“max-age=”) followed by an integer that specifies the number ofseconds the advertisement is valid." (http://www.upnp.org/specs/arch/UPnP-arch-DeviceArchitecture-v1.1.pdf)
Here spaces are not present. I try to get know why UCTT reports error for this.

**Comment by SimonChisholm** [comment]
Thanks for explaining what UCTT is.  We're members of the UPnP forum so will look out the tool ourselves and look for any further failures.
I'll apply the change you suggest for the CACHE-CONTROL header now.
