### ISSUE TITLE
Add posibility to return error code in actions

### ISSUE THREAD

**Issue by SiMet** [openhome/ohNet#19]
I'm using C++ version of library and currently there is no way to return errorCode with errorDescription from action method which extends generated Provider.

The solution could be add to DvInvocationStd method invocationReportError(TUint aCode, const std::string aDescription) which call wrapped IDviInvocation method InvocationReportError.

The other solution could be add some type of Exception with TUint and std::string constructor which handled in this methods just return passed errorCode with Description.

**Comment by SimonChisholm** [comment]
Fixed by commit 7ed54cd13d45c93a10104017b084ac298dec0067.

Use ReportError(uint32_t, string) to set error details which will be reported to the caller as a UPnP fault code.
