### ISSUE TITLE
Java Bindings for Mac OS X

### ISSUE THREAD

**Issue by Kafkalasch** [openhome/ohNet#21]
Hello,

i am having trouble obtaining the java bindings for mac os x. In the binary releases the file libohNetJni.dylib isn't included and if i try to build it myself i always get the error message:
"make: *** No rule to make target `tt', needed by `install-pkgconf'.  Stop."

**Comment by SimonChisholm** [comment]
What build command are you using?  'make ohNetJavaAll' should Java bindings plus tests.

You might need to build some auto-generated code for this.  Add 'uset4=yes' to the build command to allow for this, so

make ohNetJavaAll uset4=yes

Note that code generation uses a.NET utility so will require that you have mono installed.

**Comment by Kafkalasch** [comment]
Yes, I tried that. Getting always the same error messages as in ( http://forum.openhome.org/showthread.php?tid=1093 ) steve's first and second post. I have mono 4.2 installed and used the commands you mentioned.

**Comment by Kafkalasch** [comment]
But never mind. I have found a very old version of libohNetJni.dylib build for  mac os x and for now it is sufficient for my needs. I have just been curious about this ominous tt target.
