### ISSUE TITLE
Linking error when cross-compiling for Core-armv5

### ISSUE THREAD

**Issue by joerg-krause** [openhome/ohNet#25]
Cross-compiling ohNet for the platform Core-armv5 fails with undefined references:

```
Build/Obj/Core-armv5/Release/libTestFramework.a(TestFramework.o): In function `OpenHome::Os::ConsoleWrite(char const*)':
$HOME/output/build/ohnet-1.13.2452/Build/Include/OpenHome/OsWrapper.inl:21: undefined reference to `OsConsoleWrite'
Build/Obj/Core-armv5/Release/libTestFramework.a(TestFramework.o): In function `OpenHome::Os::TimeInUs(OsContext*)':
$HOME/output/build/ohnet-1.13.2452/Build/Include/OpenHome/OsWrapper.inl:17: undefined reference to `OsTimeInUs'
$HOME/output/build/ohnet-1.13.2452/Build/Include/OpenHome/OsWrapper.inl:17: undefined reference to `OsTimeInUs'
[...]
```

**Comment by SimonChisholm** [comment]
Can you try a clean rebuild please?  OsConsoleWrite and OsTimeInUs have implementations available.  I can't see why linking would fail to resolve only these symbols.

**Comment by joerg-krause** [comment]
How, I can disable building the tests?

**Comment by joerg-krause** [comment]
I did, several times. Maybe, because Core-armv5 sets obj-dir to Core? How can I disable building the tests?

**Comment by joerg-krause** [comment]
If I set `osdir = Posix` for *Core-armv5* libTestFramework.a is build successfully, but it fails with:

```
Build/Obj/Core-armv5/Release/libohNetCore.a(Os.o): In function `OsSemaphoreDestroy':
/home/joerg/Development/hbm10/hbm10-next/hbm10/output/build/ohnet-1.13.2452/Os/Posix/Os.c:345: undefined reference to `TEMP_FAILURE_RETRY'
```

**Comment by joerg-krause** [comment]
`TEMP_FAILURE_RETRY` is only defined for `PLATFORM_MACOSX_GNU` and `PLATFORM_FREEBSD`. Not sure, what to do about this...

**Comment by SimonChisholm** [comment]
I'd expect TEMP_FAILURE_RETRY to be defined in a system header for linux builds.  You could either look into why this isn't being picked up (issue with your toolchain or missing define?) or edit Os.c to define it for your build.

**Comment by joerg-krause** [comment]
Right, I am using a musl-based toolchain which does not have `TEMP_FAILURE_RETRY`.

How about using this one instead of testing for PLATFORM_MACOSX_GNU or PLATFORM_FREEBSD?:

```
#ifndef TEMP_FAILURE_RETRY
#define TEMP_FAILURE_RETRY(expression) \
  (__extension__                                                              \
    ({ long int __result;                                                     \
       do __result = (long int) (expression);                                 \
       while (__result == -1L && errno == EINTR);                             \
       __result; }))
#endif
```

**Comment by volumeDigital** [comment]
Hi Joerg,

I looks like you're attempting to cross-compile ohNet  for hbm10, which, I note, runs linux on armv5. However, the Core-armv5 platform you've seen is not linux :)

I think that all you need to do is:

1. Set CROSS_COMPILE appropriately
2. Run `make openhome_arch=armv5 openhome_system=Linux ohNet Tests`

This might be enough for you, but if you want to customise the cflags and linker flags, it might be easier to simply define your own platform in the Makefile, and set it up how you prefer.

Core-armv5 would be a good starting point: Makefile line 211.

HTH,
Tim

**Comment by joerg-krause** [comment]
Hi @volumeDigital , I already got it working by just using `CROSS_COMPILE=... ` make ohNet. Thanks anyway! The proper clags are set by Buildroot, which I am using to cross-compile.

However, if Core-armv5 is used as a target, the tests shouldn't be build (at least the tests requiring Posix).

**Comment by SimonChisholm** [comment]
Glad you've got your build working.  If you want to avoid building tests, you can select different build targets.  E.g.

make ohNetCore TestFramework

We haven't used the Core-armv5 build target for some time.  I've removed it to avoid any future confusion.

**Comment by joerg-krause** [comment]
Thanks!
