### ISSUE TITLE
error: size of array ‘assertC’ is negative

### ISSUE THREAD

**Issue by joerg-krause** [openhome/ohNet#27]
When building ohnet for Motorola 68040 the compilation fails with:

```
Build/Include/OpenHome/Net/Private/mDNSEmbeddedAPI.h:2931:83: error: size of array ‘assertC’ is negative
  char assertC[(sizeof(CacheRecord  )    ==  sizeof(CacheGroup)          ) ? 1 : -1];
```

I understand, that this is a compiler check. But not to handle this. Does it mean the toolchain cannot be used/needs a fix to compile ohnet?

**Comment by SimonChisholm** [comment]
This check is in third party code so I don't know the code terribly well.  It is saying that use of the toolchain needs a tweak to compile ohNet.

From the comments at lines 2917-8, maybe you need to change compiler flags to change padding in structs?
